version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: mahima
      POSTGRES_PASSWORD: newPass
      POSTGRES_DB: fiber_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: